# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObservableSynthesis' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObservableSynthesis
  pod 'RxSwift'

  target 'ObservableSynthesisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObservableSynthesisUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
